baseURL = "https://edryd.org/"
languageCode = "en-us"
title = "edryd"
name = "Ed van Bruggen"
copyright = "Copyleft © 2017-2023 Ed van Bruggen"

enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[markup]
  [markup.highlight]
    guessSyntax = true
    style = "friendly"
    tabWidth = 8
